import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const ogpAPIURL = "https://ogp-test-omega.vercel.app/api/og/わっしょい";
  console.log(ogpAPIURL);

  return (
    <html lang="ja">
      <head>
  <title>こんにちはー</title>
  {/* <meta
    property="og:image"
     content="https://og-examples.vercel.sh/api/static"
    content= {"https://ogp-test-omega.vercel.app/api/og/わっしょい"}
  /> */}
</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
