import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="ja">
      <head>
  <title>こんにちはー</title>
</head>
      <body>
        {children}
      </body>
    </html>
  );
}
